<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dsaablog"
 *
 * Auto generated by Extension Builder 2016-01-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Abasse-blog',
	'description' => '',
	'category' => 'plugin',
	'author' => 'diaby, Abasse',
	'author_email' => 'diaby_souleymane12@yahoo.fr, ahmad.abasse@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);